repos:
  - repo: local
    hooks:
      - id: ruff-formatter
        name: ruff-formatter
        entry: ruff format --check
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: ruff-linter
        name: ruff-linter
        entry: ruff check
        language: system
        types: [ python ]
        stages: [ pre-commit ]
