repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --check app
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: black
        name: black
        entry: black --check app
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: mypy
        name: mypy
        entry: mypy app
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: flake8
        name: flake8
        entry: flake8 app
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: bandit
        name: bandit
        entry: bandit -c pyproject.toml --silent -r app
        language: system
        types: [ python ]
        stages: [ pre-commit ]
